# App config
server:
  port:8080
  
spring:
  data:
    mongodb:
      database:testspringboot
      port=27017
      host=localhost
#      uri:mongodb+srv://lenin:4Oc9DaHG0Tu0FzTn@lenindev.5d0bbys.mongodb.net/?retryWrites=true&w=majority
#      database=springtest